# -*- coding: utf-8 -*-
"""MLbaiscs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JyQKTIHR7kZZCRE5tZaLAMNyxvJ2NlyQ
"""

import tensorflow as tf
import numpy as np
from tensorflow import keras

#making nn and optimizser and loss funtion
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])]) 
model.compile(optimizer='sgd', loss='mean_squared_error')

#feeding data
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float) 
ys = np.array([-2.0, 1.0, 4.0, 7.0, 10.0, 13.0], dtype=float)

#training the nn
model.fit(xs, ys, epochs=100)

print(model.predict([10.0]))